// Generated by https://quicktype.io

class Eventos{
  List<Evento> items =new List();

  Eventos();
  Eventos.fromJsonList(List<dynamic> jsonList){
    if(jsonList==null) return;
    for(var item in jsonList){
      final pelicula= new Evento.fronJsonMap(item);
      items.add(pelicula);
    }
  }
}
class Evento {
  int id;
  String nombre;
  String direccion;
  String qrUrl;
  String qrCloudId;
  String createdAt;
  String updatedAt;
  dynamic usuarioId;

  Evento({
    this.id,
    this.nombre,
    this.direccion,
    this.qrUrl,
    this.qrCloudId,
    this.createdAt,
    this.updatedAt,
    this.usuarioId,
  });
  Evento.fronJsonMap(Map<String, dynamic> json) {
     this.id=json['id'];
    this.nombre=json['nombre'];
    this.direccion=json['direccion'];
    this.qrUrl=json['qrUrl'];
    this.qrCloudId=json['qrCloudId'];
    this.createdAt=json['createdAt'];
    this.updatedAt=json['updatedAt'];
    this.usuarioId=json['usuarioId'];
    
  }
}

